export const defaultWorkouts = [
	{
		name: "Upper body",
		numberOfExercises: 5,
		lastTraining: "2020-01-01",
	},
	{
		name: "Lower body",
		numberOfExercises: 5,
		lastTraining: "2021-03-01",
	},
	{
		name: "Cardio",
		numberOfExercises: 5,
		lastTraining: "2020-09-22",
	},
	{
		name: "Pilates",
		numberOfExercises: 5,
		lastTraining: "2020-09-23",
	},
	{
		name: "Yoga",
		numberOfExercises: 5,
		lastTraining: "2020-08-23",
	},
];

export const availableExercises = [
	{
		name: "Squats",
		category: "lower body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Bench press",
		category: "upper body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Deadlift",
		category: "lower body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Biceps curl",
		category: "upper body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Triceps extension",
		category: "upper body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Leg press",
		category: "lower body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Squats",
		category: "lower body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Bench press",
		category: "upper body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Deadlift",
		category: "lower body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Biceps curl",
		category: "upper body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Triceps extension",
		category: "upper body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Leg press",
		category: "lower body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Squats",
		category: "lower body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Bench press",
		category: "upper body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Deadlift",
		category: "lower body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Biceps curl",
		category: "upper body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Triceps extension",
		category: "upper body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
	{
		name: "Leg press",
		category: "lower body",
		description: "",
		difficulty: "easy",
		recommendedRepetitions: 5,
		recommendedSets: 3,
	},
];
